name: Build and Test Setup Maven

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Match the Node.js version in your action.yml

      - name: Install dependencies
        run: npm install  # Add this step to install dependencies

      - name: Build
        run: npm run build
        
  test_default_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Maven (Default)
        uses: Contrast-Security-OSS/setup-maven@v1.0.1
        
      - name: Verify Maven Version
        run: mvn --version

  test_specific_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven_version: ['3.8.6', '3.9.0', '4.0.0-alpha-1', '3.1.1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Maven (Specific Version)
        uses: Contrast-Security-OSS/setup-maven@v1.0.1
        with:
          maven-version: ${{ matrix.maven_version }}

      - name: Verify Maven Version
        run: mvn --version | grep "${{ matrix.maven_version }}"

  test_invalid_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Maven (Invalid Version)
        uses: Contrast-Security-OSS/setup-maven@v1.0.1
        with:
            maven-version: '4.0.0-foo'
      - name: Attempt to run mvn, This should fail. 
        run: mvn --version
        continue-on-error: true #allow the action to continue if mvn fails.
      - name: Verify that the previous command failed.
        run: test $? -ne 0
